### ISSUE TITLE
Із матеріалу в публікацію. азазаза

### ISSUE THREAD

**Issue by alexbiblyj** [deamonsoft/salo#1]
Короче вовці тре дати пизди за некоректність формулювання думок і нехай він в тз вживає термін публікація. І перейменовує всі матеріали в публікації.

P.S. Пизди дати в суботу оріентовно з 14:00 до 14:05

**Comment by vov4yk-bratyk** [comment]
Саня, ти баран. Тому що в ТЗ якраз і вживається термін "публікація". Мова йшла про те, щоб вживати цей термін на front-end.
Issue треба або змінювати, або видаляти, або послати саню нахуй.

**Comment by alexbiblyj** [comment]
Не. Ти баран)
