### ISSUE TITLE
How about coffeelint?

### ISSUE THREAD

**Issue by uzumaxy** [deamonsoft/salo#4]
I thought that would be great use [CoffeeLint] (http://www.coffeelint.org) for a checking of our code. This tool may prevent a lot of bugs and help to improve code quality. What do you think about it?

**Comment by alexbiblyj** [comment]
nooooooo

**Comment by uzumaxy** [comment]
@alexbiblyj Why not?

**Comment by vov4yk-bratyk** [comment]
I think, it's a good idea.

**Comment by uzumaxy** [comment]
Great! Let's use coffeelint.
@vov4yk-bratyk Can you please write about it in our documentation?

**Comment by alexbiblyj** [comment]
no
